#!/usr/bin/env bun
/**
 * Command Renderer (single source -> per-platform command files)
 * @version 1.0.0
 *
 * Source: config/commands/<name>.md (frontmatter: name, description, argument-hint,
 * allowed-tools, optional gemini-parity: skip).
 * Outputs:
 *   .claude/commands/<name>.md   (verbatim source)
 *   .codex/prompts/<name>.md     (verbatim source)
 *   .gemini/commands/<name>.toml (Gemini custom commands are TOML only; $ARGUMENTS -> {{args}})
 * Antigravity shares .gemini/commands (per repo docs, unverified).
 *
 * Usage: bun scripts/render-commands.ts [--check]
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const ROOT = resolve(import.meta.dir, '..');
export const SOURCE_DIR = join('config', 'commands');

export interface Rendered { path: string; content: string }

/** Minimal frontmatter reader: top-level `key: value`, `>`/`|` blocks. No YAML dependency (runs in L3). */
export function splitFrontmatter(text: string): { fm: Record<string, string>; body: string } {
  const t = text.replace(/^\uFEFF/, '').replace(/\r\n/g, '\n');
  if (!t.startsWith('---\n')) return { fm: {}, body: t };
  const end = t.indexOf('\n---', 4);
  if (end < 0) return { fm: {}, body: t };
  const lines = t.slice(4, end).split('\n');
  const fm: Record<string, string> = {};
  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!m) continue;
    let v = m[2].replace(/\s+#.*$/, '').trim();
    if (v === '>' || v === '|' || v === '>-' || v === '|-') {
      const parts: string[] = [];
      while (i + 1 < lines.length && /^\s+\S/.test(lines[i + 1])) parts.push(lines[++i].trim());
      v = parts.join(' ');
    }
    fm[m[1]] = v.replace(/^["']|["']$/g, '');
  }
  const nl = t.indexOf('\n', end + 4);
  return { fm, body: nl < 0 ? '' : t.slice(nl + 1) };
}

export function renderGeminiToml(name: string, source: string): string {
  const { fm, body } = splitFrontmatter(source);
  if (/[!@]\{/.test(body)) throw new Error(`${name}: body contains Gemini !{ } or @{ } injection syntax`);
  const firstLine = body.split('\n').find(l => l.trim()) ?? name;
  const description = (fm.description || firstLine).replace(/\s+/g, ' ').trim();
  const prompt = body.replace(/\$ARGUMENTS/g, '{{args}}').replace(/^\n+/, '').replace(/\s+$/, '');
  const literal = !prompt.includes("'''");
  const tomlPrompt = literal
    ? `'''\n${prompt}\n'''`
    : `"""\n${prompt.replace(/\\/g, '\\\\').replace(/"""/g, '\\"\\"\\"')}\n"""`;
  return `# Generated by scripts/render-commands.ts from ${SOURCE_DIR.replace(/\\/g, '/')}/${name}.md - do not edit.\n` +
    `description = ${JSON.stringify(description)}\n` +
    `prompt = ${tomlPrompt}\n`;
}

export function listSources(root = ROOT): string[] {
  const dir = join(root, SOURCE_DIR);
  if (!existsSync(dir)) return [];
  return readdirSync(dir).filter(f => f.endsWith('.md')).sort().map(f => f.slice(0, -3));
}

export function renderAll(root = ROOT): Rendered[] {
  const out: Rendered[] = [];
  for (const name of listSources(root)) {
    const src = readFileSync(join(root, SOURCE_DIR, `${name}.md`), 'utf-8').replace(/\r\n/g, '\n');
    out.push({ path: join('.claude', 'commands', `${name}.md`), content: src });
    out.push({ path: join('.codex', 'prompts', `${name}.md`), content: src });
    if (!/^gemini-parity:\s*skip/m.test(splitFrontmatterRaw(src))) {
      out.push({ path: join('.gemini', 'commands', `${name}.toml`), content: renderGeminiToml(name, src) });
    }
  }
  return out;
}

function splitFrontmatterRaw(src: string): string {
  const m = src.match(/^---\n([\s\S]*?)\n---/);
  return m ? m[1] : '';
}

const MANAGED: Array<[string, string]> = [['.claude/commands', '.md'], ['.codex/prompts', '.md'], ['.gemini/commands', '.toml']];

/** Returns drift descriptions (empty = in sync). With write=true, fixes drift. */
export function sync(root = ROOT, write = false): string[] {
  const drift: string[] = [];
  const rendered = renderAll(root);
  const want = new Set(rendered.map(r => r.path.replace(/\\/g, '/')));
  for (const r of rendered) {
    const abs = join(root, r.path);
    const cur = existsSync(abs) ? readFileSync(abs, 'utf-8').replace(/\r\n/g, '\n') : null;
    if (cur !== r.content) {
      drift.push(`${cur === null ? 'missing' : 'stale'}: ${r.path}`);
      if (write) { mkdirSync(join(abs, '..'), { recursive: true }); writeFileSync(abs, r.content); }
    }
  }
  for (const [dir, ext] of MANAGED) {
    const abs = join(root, dir);
    if (!existsSync(abs)) continue;
    for (const f of readdirSync(abs)) {
      // Legacy Gemini .md commands are not loaded by Gemini CLI; treat them as stale too.
      const managedExt = f.endsWith(ext) || (dir === '.gemini/commands' && f.endsWith('.md'));
      if (managedExt && !want.has(`${dir}/${f}`)) {
        drift.push(`orphan: ${dir}/${f}`);
        if (write) rmSync(join(abs, f));
      }
    }
  }
  return drift;
}

if (import.meta.main) {
  const check = process.argv.includes('--check');
  if (listSources().length === 0) { console.error(`[FAIL] no command sources in ${SOURCE_DIR}/`); process.exit(1); }
  const drift = sync(ROOT, !check);
  if (check) {
    if (drift.length) { for (const d of drift) console.error(`[FAIL] ${d}`); console.error(`Run: bun scripts/render-commands.ts`); process.exit(1); }
    console.log(`[PASS] rendered commands in sync (${listSources().length} sources)`);
  } else {
    console.log(drift.length ? `Rendered ${drift.length} change(s):\n${drift.join('\n')}` : 'Already in sync');
  }
}
